# Setting batch to true, triggers one build at a time.
# if there is a push while a build in progress, it will wait,
# until the running build finishes, and produce a build with all the changes
# that happened during the last build.
trigger:
  batch: true
  branches:
    include:
    - release/*.*
  paths:
    include:
    - '*'
    - docs/manpages/*
    exclude:
    - '**.md'
    - eng/Version.Details.xml
    - .devcontainer/*
    - .github/*
    - docs/*
    - LICENSE.TXT
    - PATENTS.TXT
    - THIRD-PARTY-NOTICES.TXT

schedules:
  - cron: "0 8,20 * * *" # run at 8:00 and 20:00 (UTC) which is 00:00 and 12:00 (PST).
    displayName: Runtime default schedule
    branches:
      include:
      - main
    always: false # run only if there were changes since the last successful scheduled run.

pr:
  branches:
    include:
    - main
    - release/*.*
  paths:
    include:
    - '*'
    - docs/manpages/*
    exclude:
    - '**.md'
    - eng/Version.Details.xml
    - .devcontainer/*
    - .github/*
    - docs/*
    - LICENSE.TXT
    - PATENTS.TXT
    - THIRD-PARTY-NOTICES.TXT

variables:
  - template: /eng/pipelines/common/variables.yml

extends:
  template:  /eng/pipelines/common/templates/pipeline-with-resources.yml
  parameters:
    stages:
    - stage: Build
      jobs:
      #
      # Evaluate paths
      #
      - ${{ if eq(variables.dependOnEvaluatePaths, true) }}:
        - template: /eng/pipelines/common/evaluate-default-paths.yml

      #
      # Sourcebuild legs
      # We have 3 important legs for source-build:
      # - Centos.7 (ensures that RH keeps working)
      # - Linux-x64 portable (used for dependency flow and downstream PR verification)
      # - Banana.24 - Non-existent RID to ensure we don't break RIDs we don't know about.
      #
      # Running all of these everywhere is wasteful. Run Banana.24 and CentOS.7 in rolling CI,
      # Run Linux-x64 in PR.

    - template: /eng/pipelines/common/platform-matrix.yml
      parameters:
        jobTemplate: /eng/pipelines/common/global-build-job.yml
        buildConfig: Debug
        helixQueueGroup: pr
        platforms:
        - SourceBuild_Centos7_x64
        jobParameters:
          nameSuffix: Centos7SourceBuild
          extraStepsParameters:
            name: SourceBuildPackages
          timeoutInMinutes: 180

    - template: /eng/pipelines/common/platform-matrix.yml
      parameters:
        jobTemplate: /eng/pipelines/common/global-build-job.yml
        buildConfig: Release
        helixQueueGroup: pr
        platforms:
        - SourceBuild_Banana24_x64
        jobParameters:
          nameSuffix: Banana24SourceBuild
          extraStepsParameters:
            name: SourceBuildPackages
          timeoutInMinutes: 180
